---

- include: 00-deploy-zabbix-server.yml tags=zabbix

- include: 01-configure.yml tags=config

#- include: 00-deploy-mariadb.yml tags=mariadb

#- include: 00-deploy-php.yml tags=php

#- include: 00-deploy-phpMyAdmin.yml tags=phpMyAdmin

#- include: 00-deploy-HAproxy-keepalived.yml tags=ha
#  when: ha_mode is defined

