---

- hosts: 127.0.0.1
  connection: local
  user: root
  sudo: false
  gather_facts: false
  serial: 1
  tasks:
    - vsphere_guest:  
       vcenter_hostname: formacion-vcenter.ncora.local
       username: root
       password: Jamels.n4b3
       guest: "{{ vm_name }}"
       from_template: yes
       template_src: CentOS7
       cluster: Cluster-formacion
       resource_pool: "/Resources"
       vm_extra_config:
         folder: miquel-LAB

